language: java
jdk:
  - oraclejdk8

# Enable container-based architecture.
sudo: false

before_install:
  # Limit Ant's and Buck's memory usage to avoid the OOM killer.
  - export ANT_OPTS='-Xmx500m'
  - export BUCK_EXTRA_JAVA_ARGS='-Xmx500m'
  - export TERM=dumb

install:
  - git clone https://github.com/facebook/buck .buck-install || true
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/.buck-install/buck/bin

cache:
  directories:
    .buck-install
    buck-out

script:
  - python --version
  - java -version
  - buck test --exclude manual
