language: java
jdk:
  - oraclejdk8

# Enable container-based architecture.
sudo: false

addons:
  apt:
    packages:
      - python

before_install:
  # Limit Ant's and Buck's memory usage to avoid the OOM killer.
  - export ANT_OPTS='-Xmx500m'
  - export BUCK_EXTRA_JAVA_ARGS='-Xmx500m'

install:
  - mkdir -p .buck
  - cd .buck
  - git clone https://github.com/facebook/buck
  - cd buck
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/.buck/buck/bin
  - cd $TRAVIS_BUILD_DIR

cache:
  directories:
    .buck
    buck-out

script:
  - python --version
  - java -version
  - buck test --exclude manual
